language: bash
services: docker

env:
  - VERSION=2.7
  - VERSION=2.6
  - VERSION=2.5

install:
  - git clone --depth 1 https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - slash='/'; image="ruby:${VERSION}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
